# docker-compose.dev.yml - Development setup
services:
  # Frontend React App - Development
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bookstore-frontend-dev
    ports:
      - '3002:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
<<<<<<< HEAD
      - VITE_API_URL=http://localhost:3000
=======
      - VITE_API_URL=http://localhost:8000/api
>>>>>>> 40115e6 (cập nhật code mới)
    command: npm run dev
